# $FreeBSD$

MASTERDIR=	${.CURDIR}/../actspot-pkg-zabbix-proxy

PORTNAME=	actspot-pkg-zabbix-proxy4

CONFLICTS=	actspot-pkg-zabbix-proxy \
		actspot-pkg-zabbix-proxy22 \
		actspot-pkg-zabbix-proxy32 \
		actspot-pkg-zabbix-proxy34

RUN_DEPENDS=	zabbix_proxy:net-mgmt/zabbix4-proxy

ZABBIXINTERNALNAME=	zabbix-proxy4
ZABBIXTITLE=	Zabbix Proxy 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
