# $FreeBSD$

MASTERDIR=	${.CURDIR}/../actspot-pkg-zabbix-agent

PORTNAME=	actspot-pkg-zabbix-agent4

CONFLICTS=	actspot-pkg-zabbix-agent \
		actspot-pkg-zabbix-agent22 \
		actspot-pkg-zabbix-agent32 \
		actspot-pkg-zabbix-agent34

RUN_DEPENDS=	zabbix_agentd:net-mgmt/zabbix4-agent

ZABBIXINTERNALNAME=	zabbix-agent4
ZABBIXTITLE=	Zabbix Agent 4.0
ZABBIXVERSION=	40

.include "${MASTERDIR}/Makefile"
